/**
 * Code Generation Engine
 * 컴포넌트 코드 및 디자인 토큰 생성
 */

import JSZip from "jszip";
import type { GeneratedFile, TokenContext, CodeGenContext } from "./types";
import { DEFAULT_TOKENS } from "./types";
import {
  ALL_TEMPLATES,
  BUTTON_TEMPLATE,
  INPUT_TEMPLATE,
  CARD_TEMPLATE,
  BADGE_TEMPLATE,
} from "./templates";

/**
 * CSS Variables 생성
 */
export function generateCssTokens(tokens: TokenContext): string {
  const lines: string[] = [
    "/* =================================",
    "   Spaghetti Design System Tokens",
    "   Generated by Spaghetti AI",
    "   ================================= */",
    "",
    ":root {",
    "  /* Primary Colors */",
  ];

  // Primary color scale
  Object.entries(tokens.colors.primaryScale).forEach(([key, value]) => {
    lines.push(`  --color-primary-${key}: ${value};`);
  });
  lines.push(`  --color-primary: ${tokens.colors.primary};`);
  lines.push("");

  // Neutral colors (if exists)
  if (tokens.colors.neutral) {
    lines.push("  /* Neutral Colors */");
    Object.entries(tokens.colors.neutral).forEach(([key, value]) => {
      lines.push(`  --color-neutral-${key}: ${value};`);
    });
    lines.push("");
  } else {
    // Default neutral scale
    lines.push("  /* Neutral Colors */");
    const neutralScale = {
      "50": "#fafafa",
      "100": "#f5f5f5",
      "200": "#e5e5e5",
      "300": "#d4d4d4",
      "400": "#a3a3a3",
      "500": "#737373",
      "600": "#525252",
      "700": "#404040",
      "800": "#262626",
      "900": "#171717",
      "950": "#0a0a0a",
    };
    Object.entries(neutralScale).forEach(([key, value]) => {
      lines.push(`  --color-neutral-${key}: ${value};`);
    });
    lines.push("");
  }

  // Typography
  lines.push("  /* Typography */");
  lines.push(`  --font-family: ${tokens.typography.fontFamily};`);
  Object.entries(tokens.typography.fontSize).forEach(([key, value]) => {
    lines.push(`  --font-size-${key}: ${value};`);
  });
  lines.push("");

  // Spacing
  lines.push("  /* Spacing */");
  Object.entries(tokens.spacing).forEach(([key, value]) => {
    lines.push(`  --spacing-${key}: ${value};`);
  });
  lines.push("");

  // Border Radius
  lines.push("  /* Border Radius */");
  Object.entries(tokens.radius).forEach(([key, value]) => {
    lines.push(`  --radius-${key}: ${value};`);
  });

  lines.push("}");

  return lines.join("\n");
}

/**
 * Tailwind Config 생성
 */
export function generateTailwindConfig(tokens: TokenContext): string {
  const config = {
    content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
    theme: {
      extend: {
        colors: {
          primary: {
            DEFAULT: tokens.colors.primary,
            ...tokens.colors.primaryScale,
          },
          neutral: tokens.colors.neutral || {
            "50": "#fafafa",
            "100": "#f5f5f5",
            "200": "#e5e5e5",
            "300": "#d4d4d4",
            "400": "#a3a3a3",
            "500": "#737373",
            "600": "#525252",
            "700": "#404040",
            "800": "#262626",
            "900": "#171717",
            "950": "#0a0a0a",
          },
        },
        fontFamily: {
          sans: [tokens.typography.fontFamily],
        },
        fontSize: tokens.typography.fontSize,
        spacing: tokens.spacing,
        borderRadius: tokens.radius,
      },
    },
    plugins: [],
  };

  return `import type { Config } from "tailwindcss";

const config: Config = ${JSON.stringify(config, null, 2)};

export default config;
`;
}

/**
 * JSON 토큰 생성
 */
export function generateJsonTokens(tokens: TokenContext): string {
  const jsonTokens = {
    $schema: "https://design-tokens.github.io/community-group/format/",
    version: "1.0.0",
    generator: "Spaghetti AI",
    generatedAt: new Date().toISOString(),
    colors: {
      primary: {
        $value: tokens.colors.primary,
        $type: "color",
      },
      primaryScale: Object.entries(tokens.colors.primaryScale).reduce(
        (acc, [key, value]) => {
          acc[key] = { $value: value, $type: "color" };
          return acc;
        },
        {} as Record<string, { $value: string; $type: string }>
      ),
    },
    typography: {
      fontFamily: {
        $value: tokens.typography.fontFamily,
        $type: "fontFamily",
      },
      fontSize: Object.entries(tokens.typography.fontSize).reduce(
        (acc, [key, value]) => {
          acc[key] = { $value: value, $type: "fontSize" };
          return acc;
        },
        {} as Record<string, { $value: string; $type: string }>
      ),
    },
    spacing: Object.entries(tokens.spacing).reduce(
      (acc, [key, value]) => {
        acc[key] = { $value: value, $type: "spacing" };
        return acc;
      },
      {} as Record<string, { $value: string; $type: string }>
    ),
    radius: Object.entries(tokens.radius).reduce(
      (acc, [key, value]) => {
        acc[key] = { $value: value, $type: "borderRadius" };
        return acc;
      },
      {} as Record<string, { $value: string; $type: string }>
    ),
  };

  return JSON.stringify(jsonTokens, null, 2);
}

/**
 * Utils 파일 생성
 */
export function generateUtils(): string {
  return `import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
`;
}

/**
 * README 생성
 */
export function generateReadme(projectName: string): string {
  return `# ${projectName} Design System

Generated by [Spaghetti AI](https://spaghetti.ai)

## Quick Start

### 1. Install Dependencies

\`\`\`bash
npm install clsx tailwind-merge class-variance-authority
\`\`\`

### 2. Copy Files

Copy the following folders to your project:
- \`/tokens\` - Design tokens (CSS, JSON)
- \`/components\` - UI Components
- \`/lib\` - Utility functions

### 3. Import Tokens

Add to your global CSS:

\`\`\`css
@import './tokens/tokens.css';
\`\`\`

Or use the Tailwind config:

\`\`\`typescript
// tailwind.config.ts
import designSystemConfig from './tokens/tailwind.config';
export default designSystemConfig;
\`\`\`

### 4. Use Components

\`\`\`tsx
import { Button, Input, Card } from '@/components/ui';

export default function MyPage() {
  return (
    <Card>
      <Input label="Email" placeholder="Enter your email" />
      <Button>Submit</Button>
    </Card>
  );
}
\`\`\`

## Components Included

- Button (filled, outlined, text, ghost)
- Input
- Card
- Badge

## Customization

Edit \`tokens/tokens.css\` or \`tokens/tokens.json\` to customize colors, typography, spacing, and more.

---

Built with Spaghetti AI
`;
}

/**
 * 컴포넌트 인덱스 파일 생성
 */
export function generateComponentIndex(components: string[]): string {
  const exports = components.map((name) => {
    const componentName = name.charAt(0).toUpperCase() + name.slice(1);
    return `export * from "./${componentName}";`;
  });

  return exports.join("\n") + "\n";
}

/**
 * 전체 디자인 시스템 ZIP 생성
 */
export async function generateDesignSystemZip(
  context: CodeGenContext
): Promise<Blob> {
  const zip = new JSZip();
  const tokens = context.tokens || DEFAULT_TOKENS;

  // /tokens 폴더
  const tokensFolder = zip.folder("tokens");
  tokensFolder?.file("tokens.css", generateCssTokens(tokens));
  tokensFolder?.file("tokens.json", generateJsonTokens(tokens));
  tokensFolder?.file("tailwind.config.ts", generateTailwindConfig(tokens));

  // /lib 폴더
  const libFolder = zip.folder("lib");
  libFolder?.file("utils.ts", generateUtils());

  // /components/ui 폴더
  const componentsFolder = zip.folder("components/ui");

  // 기본 컴포넌트 추가
  const componentFiles = [
    { name: "Button", content: BUTTON_TEMPLATE.template },
    { name: "Input", content: INPUT_TEMPLATE.template },
    { name: "Card", content: CARD_TEMPLATE.template },
    { name: "Badge", content: BADGE_TEMPLATE.template },
  ];

  componentFiles.forEach(({ name, content }) => {
    componentsFolder?.file(`${name}.tsx`, content);
  });

  // index.ts 생성
  componentsFolder?.file(
    "index.ts",
    generateComponentIndex(componentFiles.map((c) => c.name))
  );

  // README.md
  zip.file("README.md", generateReadme(context.projectName));

  // ZIP 생성
  return await zip.generateAsync({ type: "blob" });
}

/**
 * 개별 파일 생성
 */
export function generateFiles(context: CodeGenContext): GeneratedFile[] {
  const tokens = context.tokens || DEFAULT_TOKENS;
  const files: GeneratedFile[] = [];

  // Token files
  files.push({
    path: "tokens/tokens.css",
    content: generateCssTokens(tokens),
    type: "token",
  });

  files.push({
    path: "tokens/tokens.json",
    content: generateJsonTokens(tokens),
    type: "token",
  });

  files.push({
    path: "tokens/tailwind.config.ts",
    content: generateTailwindConfig(tokens),
    type: "config",
  });

  // Utils
  files.push({
    path: "lib/utils.ts",
    content: generateUtils(),
    type: "util",
  });

  // Components
  ALL_TEMPLATES.forEach((template) => {
    files.push({
      path: `components/ui/${template.name}.tsx`,
      content: template.template,
      type: "component",
    });
  });

  // Component index
  files.push({
    path: "components/ui/index.ts",
    content: generateComponentIndex(ALL_TEMPLATES.map((t) => t.name)),
    type: "component",
  });

  // README
  files.push({
    path: "README.md",
    content: generateReadme(context.projectName),
    type: "component",
  });

  return files;
}
